export const EMOTION_CONFIG = {
  happy: {
    label: 'Happy',
    emoji: '😊',
    theme: 'theme-happy',
    accentColor: '#F59E0B',
    bgGradient: 'linear-gradient(135deg, #1A1200, #2A1F00)',
    message: 'You look happy! Keep that energy going.',
    breathePrompt: null,
    confetti: true,
    fontScale: '1.05',
  },
  sad: {
    label: 'Sad',
    emoji: '😢',
    theme: 'theme-sad',
    accentColor: '#6B9EE8',
    bgGradient: 'linear-gradient(135deg, #0B0F1A, #111827)',
    message: 'It\'s okay to feel this way. Take it one step at a time.',
    breathePrompt: null,
    confetti: false,
    fontScale: '1.0',
  },
  angry: {
    label: 'Angry',
    emoji: '😠',
    theme: 'theme-angry',
    accentColor: '#60A5FA',
    bgGradient: 'linear-gradient(135deg, #0F0A0A, #1A0F0F)',
    message: 'Take a slow breath. Let\'s work through this together.',
    breathePrompt: 'Breathe in... breathe out...',
    confetti: false,
    fontScale: '0.95',
  },
  fearful: {
    label: 'Fearful',
    emoji: '😨',
    theme: 'theme-fearful',
    accentColor: '#84CC16',
    bgGradient: 'linear-gradient(135deg, #0F100A, #191A12)',
    message: 'You\'re safe here. Everything is under control.',
    breathePrompt: null,
    confetti: false,
    fontScale: '1.08',
  },
  surprised: {
    label: 'Surprised',
    emoji: '😮',
    theme: 'theme-surprised',
    accentColor: '#A78BFA',
    bgGradient: 'linear-gradient(135deg, #0D0A1A, #150F28)',
    message: 'Something unexpected? Let\'s explore it together!',
    breathePrompt: null,
    confetti: false,
    fontScale: '1.05',
  },
  disgusted: {
    label: 'Disgusted',
    emoji: '😒',
    theme: 'theme-disgusted',
    accentColor: '#10B981',
    bgGradient: 'linear-gradient(135deg, #0A100C, #0F1A12)',
    message: 'Let\'s clear the air and start fresh.',
    breathePrompt: null,
    confetti: false,
    fontScale: '0.98',
  },
  neutral: {
    label: 'Neutral',
    emoji: '😐',
    theme: 'theme-neutral',
    accentColor: '#3B82F6',
    bgGradient: 'linear-gradient(135deg, #070B14, #0D1424)',
    message: 'Focused and ready. How can I help you today?',
    breathePrompt: null,
    confetti: false,
    fontScale: '1.0',
  },
}

export const EMOTION_COLORS = {
  happy:     '#F59E0B',
  sad:       '#6B9EE8',
  angry:     '#EF4444',
  fearful:   '#84CC16',
  surprised: '#A78BFA',
  disgusted: '#10B981',
  neutral:   '#3B82F6',
}
